name: Issue Response Bot

on:
  issues:
    types: [opened]

permissions:
  issues: write  # 이슈에 대한 쓰기 권한을 부여

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28.0 requests  # 특정 버전으로 설치

      - name: Generate Response
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python .github/workflows/respond_to_issue.py
